# Generated by Django 3.1.1 on 2020-11-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_auto_20201104_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
