# Generated by Django 3.1.1 on 2020-11-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_emailphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailphone',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emailphone',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
