# Generated by Django 3.1.1 on 2020-11-05 03:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_auto_20201104_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitableprojects',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
