# Generated by Django 3.1.1 on 2020-11-07 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Page'},
        ),
    ]
