# Generated by Django 3.1.1 on 2020-11-27 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0009_auto_20201118_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitableprojects',
            name='image',
            field=models.ImageField(blank=True, default='D:/django/career_stimulus/charity/static/images/no_image.png', null=True, upload_to='uploads/images'),
        ),
        migrations.CreateModel(
            name='ProjectsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/images')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.charitableprojects')),
            ],
            options={
                'verbose_name_plural': 'Project Image',
            },
        ),
    ]
