# Generated by Django 3.1.1 on 2021-01-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0011_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Payment Info'},
        ),
        migrations.AlterField(
            model_name='user',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
