# Generated by Django 3.1.1 on 2021-10-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0013_writetousmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writetousmodel',
            name='queries',
            field=models.TextField(max_length=300),
        ),
    ]
