# Generated by Django 3.1.1 on 2021-10-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0014_auto_20211003_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writetousmodel',
            old_name='queries',
            new_name='feedback',
        ),
    ]
